### PR TITLE
redirection created

### PR DESCRIPTION
**Pull request by Dorcastunmise**
A github logo has been added for the user to click on to get redirected to your repo.

### CODE REVIEW

**Comment by Dorcastunmise** [comment]
@pushkaraj2007 let me know when you get the pull request please.

**Comment by Dorcastunmise** [comment]
Oooh, you chose someone else already. Have a wonderful day.

**Comment by pushkaraj2007** [comment]
> @pushkaraj2007 let me know when you get the pull request please. 

Will merge it soon, sorry for the wait.

**Comment by pushkaraj2007** [comment]
> Oooh, you chose someone else already. Have a wonderful day.

You too.

Keep contributing. 🚀🚀

**Comment by Dorcastunmise** [comment]
Noted

**Comment by pushkaraj2007** [comment]
> Noted

Do you have any new feature idea, that we can add.

**Comment by Dorcastunmise** [comment]
Well, I was thinking if you could add something that slides out/in once the url of the webpage is viewed

**Comment by pushkaraj2007** [comment]
Do you mean like a type of loading animation?

**Comment by pushkaraj2007** [comment]
Issue has been already resolved!!

**Pull request closed without merging**
