### PR TITLE
I added the feature of the "USER" being able to choose a background image!

### PR DESCRIPTION
**Pull request by abitsalihu**
I have added the necessary changes to add a feature where the "user" has the ability to choose between 7 different pictures, or a gradient, and added the necessary code that it will be flexible across all view sizes with no need of @mediaqueries!

Below is a video of how this feature will work, and how it will look across different devices!

https://user-images.githubusercontent.com/94648837/190162479-80a24f8f-ddfc-439e-9d12-6ebf2f96567f.mov

Desktop view: 

Screen Shot 2022-09-14 at 15 09 31

Tablet view: 

Screen Shot 2022-09-14 at 15 00 20

Mobile view:

Screen Shot 2022-09-14 at 15 00 27

### CODE REVIEW

**Comment by pushkaraj2007** [comment]
Looks really great 🔥

But getting some minor problems, don't worry I'll fix it. 

Thanks for contributing!!

**Comment by abitsalihu** [comment]
@pushkaraj2007 what seems to be the problem?

**Comment by pushkaraj2007** [comment]
Like changing the URL from images/xyz.jpg to Images/xyz.jpg

Because it's case sensitive and it's making problems in production. 

If you want you can change the URL of all images like that and make a PR. 

It's a minor bug, but creates a big problem. 

After that I'll close the issue.

**Comment by abitsalihu** [comment]
@pushkaraj2007 unfortunately I have a lot of work to do and I can't do that right now,  but I'm sure someone would love to try to since it's a "good first issue".

**Comment by pushkaraj2007** [comment]
@abitsalihu No problems! It's just a minor issue, I'll fix it soon.

**Pull request merged**
